NewsStudyRostelecom/NewsStudyRostelecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views as main_views
handler404 = main_views.custom_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug/__', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Новости нашей Галактики"

NewsStudyRostelecom/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.index, name='home'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('', views.about, name='about'),
]

NewsStudyRostelecom/news/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.news, name='news_index'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('article_list/', views.ArticleListView.as_view(), name='search_news'),
    path('<int:pk>', views.ArticleDetailView.as_view(), name='news_detail'),
    path('update/<int:pk>', views.ArticleUpdateView.as_view(), name='news_update'),
    path('delete/<int:pk>', views.ArticleDeleteView.as_view(), name='news_delete'),
    path('news_input/', views.news_input, name='news_input'),
    path('news_request/', views.news_request, name='news_request'),
    path('news_subscribe/', views.news_subscribe, name='news_subscribe'),
]

NewsStudyRostelecom/news/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

class Tag(models.Model):
    title = models.CharField(max_length=80, verbose_name='Название')
    status = models.BooleanField(default=True, verbose_name='Статус')
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['title','status']
        verbose_name = 'Тэг'
        verbose_name_plural ='Тэги'

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=1)

class Article(models.Model):
    categories_list = (('A', 'Астрономия'),
                  ('K', 'Космонавтика'),
                  ('AF', 'Астрофизика'),
                  ('G', 'Геология'))
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Автор')
    title = models.CharField('Название новости', max_length=150, default='', validators = [MinLengthValidator(10)], null=False)
    anouncement = models.TextField('Аннотация', max_length=1250, validators = [MinLengthValidator(10)], null=False)
    source = models.URLField('Источник', null=True)
    sourcename = models.CharField('Название источника', max_length=150, validators = [MinLengthValidator(2)], null=False)
    text = RichTextField('Текст новости', validators = [MinLengthValidator(50)], null=False)
    date = models.DateTimeField('Дата публикации', auto_created=True)
    categories = models.CharField(choices=categories_list, max_length=20, verbose_name='Категории')
    tags = models.ManyToManyField(to=Tag, blank=True)
    status = models.BooleanField(default=False, verbose_name='Опубликовано')
    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return f'Статья №{self.id} от {str(self.date)[:16]} "{self.title}"'

    def get_absolute_url(self):
        return f'/news/{self.pk}'

    #метаданные модели
    def tag_list(self):
        s = ''
        for t in self.tags.all():
            s+=t.title+' '
        return s

    def image_tag(self):
        image = Image.objects.filter(article=self)
        if image:
            return mark_safe(f'<img src="{image[0].image.url}" height="50px" width="auto" />')
        else:
            return '(no image)'

    def get_views(self):
        return self.views.count()

    class Meta:
        ordering = ['title','date']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

class Subscriber(models.Model):
    last_name = models.CharField(max_length=50, verbose_name='Фамилия', default='', null=False)
    first_name = models.CharField(max_length=50, verbose_name='Имя', default='', null=False)
    email = models.EmailField(max_length=254, verbose_name='Адрес электронной почты', null=False)

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.email}"

    class Meta:
        ordering = ['last_name']
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

class Image(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, blank=True)
    image = models.ImageField(upload_to='news_images/', blank=True, null=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image is not None:
            return mark_safe(f'<img src="{self.image.url}" height="50px" width="auto"/>')
        else:
            return '(no image)'

    class Meta:
        ordering = ['title']
        verbose_name = 'Фото'
        verbose_name_plural = 'Фото'

class ViewCount(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,
                                related_name='views', verbose_name='Новость')
    ip_address = models.GenericIPAddressField(verbose_name='ip-адрес')
    view_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')

    class Meta:
        verbose_name = 'Счетчик просмотров'
        verbose_name_plural = 'Счетчики просмотров'
        ordering=('-view_date',)
        indexes = [models.Index(fields=['-view_date'])]

    def __str__(self):
        return self.article.title

NewsStudyRostelecom/main/forms.py
# from django import forms
# from .models import Demo
# from django.forms.widgets import TextInput, FileInput
# class DemoForm(forms.ModelForm):
#     class Meta:
#         model = Demo
#         fields = ('title','image')
#         widgets={
#             'title': TextInput(attrs={'class':'input','placeholder':'Заголовок'}),
#             'image': FileInput(attrs={'class':'input','placeholder':'image'}),
#         }

NewsStudyRostelecom/news/forms.py
from django import forms
from django.core.validators import ValidationError
from django.forms import ModelForm, Textarea, CheckboxSelectMultiple, Select
from .models import *


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = '__all__'
        widgets = {
            'last_name': Textarea(attrs={'cols': 96, 'rows': 1}),
            'first_name': Textarea(attrs={'cols': 101, 'rows': 1}),
        }

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if not last_name:
            raise ValidationError('Last name is required')
        return last_name

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name:
            raise ValidationError('First name is required')
        return first_name

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email:
            raise ValidationError('Email is required')
        return email

    def save(self):
        last_name = self.cleaned_data['last_name']
        first_name = self.cleaned_data['first_name']
        email = self.cleaned_data['email']
        Subscriber.objects.create(last_name=last_name, first_name=first_name, email=email)

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if len(last_name) < 2:
            raise ValidationError('Фамилия не может быть меньше 2 знаков')
        return last_name

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if len(first_name) < 2:
            raise ValidationError('Имя не может быть меньше 2 знаков')
        return first_name


class ArticleForm(ModelForm):
    image_field = MultipleFileField()
    class Meta:
        model = Article
        fields = ['categories',
                  'title',
                  'anouncement',
                  'text',
                  'source',
                  'sourcename',
                  'tags',
                  ]
        widgets = {
            'categories': Select(),
            'title': Textarea(attrs={'cols': 80, 'rows': 1}),
            'anouncement': Textarea(attrs={'cols': 87, 'rows': 7}),
            'source': Textarea(attrs={'cols': 88, 'rows': 1}),
            'sourcename': Textarea(attrs={'cols': 78, 'rows': 1}),
            'tags': CheckboxSelectMultiple(),
        }

class ArticleRequestForm(ModelForm):
    image_field = MultipleFileField()
    class Meta:
        model = Article
        fields = ['categories',
                  'title',
                  'anouncement',
                  'text',
                  'source',
                  'sourcename',
                  ]
        widgets = {
            'categories': Select(),
            'title': Textarea(attrs={'cols': 80, 'rows': 1}),
            'anouncement': Textarea(attrs={'cols': 87, 'rows': 7}),
            'source': Textarea(attrs={'cols': 88, 'rows': 1}),
            'sourcename': Textarea(attrs={'cols': 78, 'rows': 1}),
        }

NewsStudyRostelecom/main/views.py
import json

from django.shortcuts import render
from django.views.generic import ListView
from news.models import Article
from .models import *
from django.http import HttpResponse


def index(request):
    articles = Article.objects.all()
    context = {
        'articles':articles,
    }

    return render(request, 'main/index.html', context)

def search_auto(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        q = request.GET.get('term','')
        articles = Article.objects.filter(title__icontains=q)
        results =[]
        for a in articles:
            results.append(a.title)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data,mimetype)

def custom_404(request, exception):
    return render(request, 'main/custom_404.html')

def about(request):
    return render(request, 'main/about.html')

NewsStudyRostelecom/news/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView, UpdateView, ListView
from .utils import ViewCountMixin
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
import datetime
import json
from users.models import FavoriteArticle
from django.db.models import Count


def search_auto(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        q = request.GET.get('term','')
        articles = Article.objects.filter(title__icontains=q)
        results =[]
        for a in articles:
            results.append(a.title)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data,mimetype)


class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'
    context_object_name = "articles"
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('search_input')
        articles = Article.objects.filter(title__icontains=query)
        return articles

class ArticleDetailView(ViewCountMixin, DetailView):
    model = Article
    template_name = 'news/news_detail.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_object = self.object
        images = Image.objects.filter(article=current_object)
        context['images'] = images
        return context

class ArticleUpdateView(UpdateView):
    model = Article
    success_url = reverse_lazy('user_profile')
    template_name = 'news/news_input.html'
    fields = ['categories','title','anouncement','text','source','sourcename','tags']

class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('user_profile')
    template_name = 'news/news_delete.html'

@login_required(login_url="/")
def news_input(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            if current_user.is_staff == True:
                if current_user.id != None:
                    new_article = form.save(commit=False)
                    new_article.author = current_user
                    new_article.date = datetime.date.today()
                    new_article.status = True
                    new_article.save()
                    form.save_m2m()
                    for img in request.FILES.getlist('image_field'):
                        Image.objects.create(article=new_article, image=img, title=img.name)
                    return redirect('news_index')
    else:
        form = ArticleForm()
    return render(request, 'news/news_input.html', {'form': form})

def news_subscribe(request):
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Ваш запрос на рассылку новостей успешно отправлен!')
            return redirect('home')
    else:
        form = SubscribeForm()
    return render(request,'news/news_subscribe.html', {'form': form})

def news(request):
    favorite_article = FavoriteArticle.objects.filter(user=request.user)
    categories = Article.categories_list
    author_list = User.objects.filter(article__isnull=False).filter(article__status=True).distinct()
    if request.method == "POST":
        selected_author = int(request.POST.get('author_filter'))
        selected_category = int(request.POST.get('category_filter'))
        request.session['author_filter'] = selected_author
        request.session['category_filter'] = selected_category
        if selected_author == 0:
            articles = Article.published.all()
        else:
            articles = Article.published.filter(author=selected_author)
        if selected_category != 0:
            articles = articles.filter(categories__icontains=categories[selected_category-1][0])
    else:
        value = request.session.get('search_input')
        if value != None:
            articles = Article.published.filter(title__icontains=value)
        else:
            selected_author = request.session.get('author_filter')
            selected_category = request.session.get('category_filter')
            articles = Article.published.all()
            if selected_author != None and int(selected_author) != 0:
                articles = articles.filter(author=selected_author)
            else:
                selected_author = 0
            if selected_category != None and int(selected_category) != 0:
                articles = articles.filter(categories__icontains=categories[selected_category - 1][0])
            else:
                selected_category = 0
    articles = articles.order_by('-date')
    total = len(articles)
    p = Paginator(articles, 4)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    context = {
        'articles': page_obj,
        'author_list': author_list,
        'selected_author': selected_author,
        'total': total,
        'categories': categories,
        'selected_category': selected_category,
        'favorite_article': favorite_article,
    }
    return render(request, 'news/news.html', context)


@login_required(login_url="/")
def news_request(request):
    if request.method == 'POST':
        form = ArticleRequestForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            if current_user.is_staff == False:
                if current_user.id != None:
                    new_article = form.save(commit=False)
                    new_article.author = current_user
                    new_article.date = datetime.date.today()
                    new_article.save()
                    form.save_m2m()
                    for img in request.FILES.getlist('image_field'):
                        Image.objects.create(article=new_article, image=img, title=img.name)
                    return redirect('news_index')
    else:
        form = ArticleRequestForm()
    return render(request, 'news/news_request.html', {'form': form})

NewsStudyRostelecom/main/templates/main/about.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
{% load bootstrap5 %}
<html xmlns="http://www.w3.org/1999/xhtml">
<html lang="ru">

<head>
    {%bootstrap_css%}
    {%bootstrap_javascript%}
    <title>Новости нашей Галактики</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/font/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/font/font.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/bootstrap.min.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/style.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/responsive.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/jquery.bxslider.css" media="screen"/>
    <script src="https://kit.fontawesome.com/b91fb3443a.js"></script>
</head>
<body>

<div class="body_wrapper">
    <div class="center">
        {% block header %} {% include 'main/header.html' %} {% endblock %}<br>
        <h6 class="title"></h6>
        <div class="container" style="line-height:1.5;">
            <h1 style="text-align:center">Добро пожаловать на сайт &quot;Новости нашей Галактики&quot;!</h1>
            <hr/>
            <div style="text-align:justify"><span style="font-size:16px">&nbsp;&nbsp;&nbsp;&nbsp;Мы собираем и публикуем на сайте все интересные новости и события, произошедшие в космической сфере. Поделитесь новостями о космосе, полученными из других источников: зарегистрируйтесь на сайте, подайте заявку на публикацию заинтересовавшей вас новости (с указанием ссылки на источник). Мы обязательно ее рассмотрим и опубликуем, чтобы другие пользователи сайта могли узнать новое о космосе. Вы всегда можете добавить любую новость в избранное и наслаждаться чтением в любое удобное для вас время, не переходя по бесконечным ссылкам в сети интернет!  </span>
            </div>
            <hr/>
            <h2 style="text-align:center">Обзор функциональности сайта</h2>

            <div style="text-align:justify">
            </div>

            <ul>
                <li style="text-align:justify">
                    <div><span style="font-size:16px"><a href="{% url 'home' %}" class="link-underline-primary"><b>Фотогалерея</b></a> на главной странице с переходом на детальное описание новости.</span>
                    </div>
                </li>
                <li style="text-align:justify">
                    <div><span style="font-size:16px">Просмотр новостей на странице со <a href="{% url 'news_index' %}" class="link-underline-primary"><b>списком новостей</b></a>.</span></div>
                </li>
                <li style="text-align:justify">
                    <div><span style="font-size:16px">Чтение детального описания статей (для этого необходимо кликнуть по фото новости).</span></div>
                </li>
                <li style="text-align:justify">
                    <div><span style="font-size:16px">Поиск новостей по заголовку (строка поиска расположена в правой верхней части экрана).</span></div>
                </li>
                <li style="text-align:justify">
                    <div><span style="font-size:16px">Фильтр новостей по автору, категории (доступен в <a href="{% url 'news_index' %}" class="link-underline-primary"><b>списке новостей)</b></a>.</span></div>
                </li>
                <li style="text-align:justify">
                    <div><span style="font-size:16px">Отправка заявки на <a href="{% url 'news_subscribe' %}" class="link-underline-primary"><b>рассылку новостей</b></a>.</span></div>
                </li>
                <li style="text-align:justify">
                    <div><span style="font-size:16px"><a href="{% url 'registration' %}"><b>Регистрация</b></a> и <a href="{% url 'login' %}"><b>вход</b></a> в профиль.</span></div>
                </li>
                <li style="text-align:justify">
                    <div><span style="font-size:16px">Возможность подачи заявки на создание новости и добавление новостей в избранное после регистрации на сайте.</span>
                    </div>
            </ul>

            <hr/>

            <div style="text-align:justify"><span style="font-size:16px">&nbsp;&nbsp;&nbsp;&nbsp;Если вы обнаружите ошибку, неправильное отображение или сбой функциональности, пожалуйста, отправьте отчет с описанием каждой найденной проблемы, прикладывая сохраненные снимки экрана. Используйте <a href="{% url 'contact_page' %}" class="link-underline-primary"><b>форму обратной связи</b></a> на сайте.</span>
            </div>

            <hr/>
        </div>
    </div>
    <br>
    <div class="row">
    <div class="col-lg-6" align="center">
        <a class="readmore" href="{% url 'home' %}"><input class="btn btn-danger" type="submit"
                                                                              value="В галерею"></a>
    </div>
    <div class="col-lg-6" align="center">
        <a class="readmore" href="{% url 'news_index' %}"><input class="btn btn-danger" type="submit"
                                                                              value="Читать новости"></a>
    </div>
    </div>
    <div class="content_area">
        <h6 class="title"></h6>
    </div>


    {% block footer %} {% include 'main/footer.html' %} {% endblock %}
</div>
<script type="text/javascript" src="{% static 'main/' %}assets/js/jquery-min.js"></script>
<script type="text/javascript" src="{% static 'main/' %}assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'main/' %}assets/js/jquery.bxslider.js"></script>
<script type="text/javascript" src="{% static 'main/' %}assets/js/selectnav.min.js"></script>
<script type="text/javascript">
    selectnav('nav', {
        label: 'Меню',
        nested: true,
        indent: ''
    });
    selectnav('f_menu', {
        label: 'Меню',
        nested: true,
        indent: ''
    });
    $('.bxslider').bxSlider({
        mode: 'fade',
        captions: true
    });
</script>
<script src="https://kit.fontawesome.com/b91fb3443a.js" crossorigin="anonymous"></script>
<!-- jQuery !-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<!-- jQuery UI !-->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script>
    $(function() {
        $("#search_input").autocomplete({
            source: "search_auto/",
            select: function (event, ui) { //item selected
                AutoCompleteSelectHandler(event, ui)
            },
            minLength: 2,
        });
    });

  function AutoCompleteSelectHandler(event, ui)
  {
    var selectedObj = ui.item;
  }
</script>
</body>
</html>

NewsStudyRostelecom/main/templates/main/footer.html
{% load static %}

<!--<div class="footer_top_area"></div>-->
<div class="copyright_text">
    <p>Copyright &copy; 2023 Новости нашей Галактики | Все права защищены</p>
    <p>Торговые марки и изображения, используемые в дизайне, являются собственностью их соответствующих владельцев и
        используются только в демонстрационных целях.</p>
</div>

NewsStudyRostelecom/main/templates/main/header.html
{% load static %}
<div class="container-fluid">
    <div class="header_area">
        <div class="row">
            <div class="col-lg-8">
                <div class="logo floatleft">
                    <p><a href="{% url 'about' %}"><img src="{% static 'main/' %}images/logo5.png" alt="Иконка"/></a></p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="social"></div>
                <div class="search">
                    {% block search %} {% include 'news/search.html' %} {% endblock %}
                </div>
            </div>
        </div>
    </div>
    {% block sidebar %} {% include 'main/sidebar.html' %} {% endblock %}

NewsStudyRostelecom/main/templates/main/index.html
{% extends 'main/mainbase.html' %}
{% load static %}
{% block title %} Главная страница {% endblock %}

NewsStudyRostelecom/main/templates/main/mainbase.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
{% load bootstrap5 %}
<html xmlns="http://www.w3.org/1999/xhtml">
<html lang="ru">

<head>
    {%bootstrap_css%}
    {%bootstrap_javascript%}
    <title>Главная страница</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/font/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/font/font.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/bootstrap.min.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/style.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/responsive.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/' %}assets/css/jquery.bxslider.css" media="screen"/>
    <script src="https://kit.fontawesome.com/b91fb3443a.js"></script>
</head>
<body>

<div class="body_wrapper">
    <div class="center">
        {% block header %} {% include 'main/header.html' %} {% endblock %}
        {% block slider %} {% include 'main/slider.html' %} {% endblock %}
        {% block footer %} {% include 'main/footer.html' %} {% endblock %}
    </div>
</div>
<script type="text/javascript" src="{% static 'main/' %}assets/js/jquery-min.js"></script>
<script type="text/javascript" src="{% static 'main/' %}assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'main/' %}assets/js/jquery.bxslider.js"></script>
<script type="text/javascript" src="{% static 'main/' %}assets/js/selectnav.min.js"></script>
<script type="text/javascript">
    selectnav('nav', {
        label: 'Меню',
        nested: true,
        indent: ''
    });
    selectnav('f_menu', {
        label: 'Меню',
        nested: true,
        indent: ''
    });
    $('.bxslider').bxSlider({
        mode: 'fade',
        captions: true
    });
</script>
<script src="https://kit.fontawesome.com/b91fb3443a.js" crossorigin="anonymous"></script>
<!-- jQuery !-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
<!-- jQuery UI !-->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script>
        $(function() {
            $("#search_input").autocomplete({
                source: "search_auto/",
                select: function (event, ui) { //item selected
                    AutoCompleteSelectHandler(event, ui)
                },
                minLength: 2,
            });
        });

      function AutoCompleteSelectHandler(event, ui)
      {
        var selectedObj = ui.item;
      }
</script>
</body>
</html>

NewsStudyRostelecom/main/templates/main/slider.html
{% load static %}

<div class="container-fluid">
    <div class="slider_area">
        <div class="content_area">
            <h2 class="title">ФОТОГАЛЕРЕЯ</h2>
        </div>
        <div class="slider">
            <ul class="bxslider">
                {% for n in articles %}
                {% if n.image_set.all %}
                {% if n.status == True %}
                <a href="{{ n.get_absolute_url }}">
                <li>
                        {% for image in n.image_set.all %}
                        {% if n.image_set.all|length == 1 %}
                        <img src="{{ image.image.url }}"
                             style="margin:auto; height:520px; width:auto; border-radius:5px;" alt=""
                             title="{{ n.title }}"/>
                        {% endif %}
                        {% endfor %}
                        {% if n.image_set.all|length > 1 %}
                        <img src="{{ n.image_set.all.0.image.url }}"
                             style="margin:auto; height:520px; width:auto; border-radius:5px"
                             alt="" title="{{ n.title }}"/>
                        {% endif %}
                </li>
                    </a>
                {% endif %}
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <h6 class="title"></h6>
        <div class="container">
            <a class="readmore" href="{% url 'news_index' %}"><input class="btn btn-danger" type="submit"
                                                                     value="К списку новостей"></a></div>
        <div class="content_area">
            <h6 class="title"></h6>
        </div>
    </div>
</div>